version: '3.8'

services:
  mediafusion:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./mediafusion.local.pem:/etc/ssl/certs/mediafusion.local.pem
      - ./mediafusion.local-key.pem:/etc/ssl/private/mediafusion.local-key.pem
    ports:
      - "443:443"
    depends_on:
      - mediafusion

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dramatiq-worker:
    build:
      dockerfile: Dockerfile
    command: ["pipenv", "run", "dramatiq", "api.task", "-p", "1", "-t", "1", "--queues", "scrapy"]
    env_file:
      - .env
    depends_on:
      - mongodb

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      UMASK: "002"
    ports:
      - "9696:9696"
    volumes:
      - prowlar-config:/config

volumes:
  mongo-data:
  prowlar-config:
